### ISSUE TITLE
Set Apps to not use eGPU

### ISSUE THREAD

**Issue by gedoensmax** [mayankk2308/set-egpu#12]
It would be grat if all my Apps would run on internal Graphics so that all my NVRAM on eGPU is free for CUDA (more specific Tensorflow). From my point of view this is not possible at the moment right ?

**Comment by mayankk2308** [comment]
Sorry for not responding earlier. I missed this one. I believe something like GfxCardStatus could force use of iGPU, but I have not researched this possibility with respect to eGPUs at all. This feature is beyond the purview of set-eGPU.
