### ISSUE TITLE
Doesn't work with Catalina 10.15 beta

### ISSUE THREAD

**Issue by timharek** [mayankk2308/set-egpu#13]
I cannot seem to get this to work with macOS Catalina 10.15 beta (19A501i), it doesn't update any application to be set to "Prefer external graphics card". 

I have given the **terminal** all the permissions needed, but still nothing. The script opens all the different applications "Show info" boxes, but doesn't update the checkbox.

*DISCLAIMER: I have not used this software with Mojave*

**Comment by mayankk2308** [comment]
Thank you for the report. Will look into this when possible.

**Comment by mayankk2308** [comment]
@adipid I tried the script on **macOS Catalina Developer Beta 5**, but could not reproduce the issue. The issue I encountered was that the script did not seem to consider all the applications. However, it was able to successfully update the checkboxes for preferring external GPUs. I shall investigate further.

**Comment by timharek** [comment]
I haven't tried since **Beta 2** I think, so I can also give it another try when I get the chance with my _eGPU_.

**Comment by mayankk2308** [comment]
As of macOS Catalina Beta 7, all seems to working as normal. It is important to ensure that all requested permissions for Terminal are granted (typically automations and accessibility). Please open a new issue if you face problems on a release build of macOS.
