### ISSUE TITLE
Nested Applications (e.g. Xcode)

### ISSUE THREAD

**Issue by nabilfreeman** [mayankk2308/set-egpu#17]
Hey there, thanks for making such a useful script. Hopefully Apple makes this easier in a later Mac version.

I noticed that apps like the iOS Simulator are embedded in a directory inside `Xcode.app` and aren't picked up by `set-eGPU`. I had to enable it manually.

I think by doing a recursive search inside `/Applications` you'd be able to detect these.

Is it something you're aware of and would you like me to contribute a PR to fix?

**Comment by nabilfreeman** [comment]
<img width="662" alt="Screenshot 2020-06-12 at 14 27 08" src="https://user-images.githubusercontent.com/2470659/84507513-d96d4b80-acb8-11ea-8824-b0916c5fb80c.png">

**Comment by mayankk2308** [comment]
Unfortunately Apple explained to me why they considered and then abandoned a single switch for setting a global preference, so you might not see that feature anytime soon :)

Anyway, the search depth was limited as a compromise between coverage vs. speed. When last tested, deep depth searches were taking too long. I will consider incorporating this if I discover a better way to set eGPU preferences in the future. Leaving this open as an enhancement.

**Comment by mayankk2308** [comment]
I'll consider this enhancement with the approach suggested in #19.
