### ISSUE TITLE
[question] unix applications (e.g. Steam games)

### ISSUE THREAD

**Issue by rkitover** [mayankk2308/set-egpu#18]
I tried to enable "prefer eGPU" for The Talos Principle, a Steam game, using both the installed shortcut and the script, but this has no effect.

When I browse the game files in Steam with Manage -> Show Local Files, and then open Get Info on the actual game executable, it shows as a "unix application" and has no setting for "prefer eGPU".

Is there any way to enable the eGPU for such executables?

**Comment by mayankk2308** [comment]
Probably something like this: https://egpu.io/forums/postid/74029/

**Comment by rkitover** [comment]
Will try this, thank you!
