### ISSUE TITLE
bug when a monitor is plugged

### ISSUE THREAD

**Issue by KevinHuddy** [mayankk2308/set-egpu#2]
Since i installed set-egpu i can't listen to a movie on my macbook while working on my monitor. graphics glitch / freeze a lot. When i unplug my egpu everything go back to normal. How can i uninstall set-egpu the right way ? Thanks in advance.

**Comment by mayankk2308** [comment]
Reset all preferences using option 4. 

It is recommended to set eGPU on per-app basis.

**Comment by KevinHuddy** [comment]
Already done. Guess i'll try again & restart. Thanks for the fast answer!

**Comment by mayankk2308** [comment]
@kevinhuddy Was the issue resolved? Please provide an update when possible :)

**Comment by mayankk2308** [comment]
This issue should not be related to set-eGPU. If you are using an NVIDIA eGPU, this is a known issue.
