### ISSUE TITLE
Zoomed in Video on MBP 2017 & Premiere Pro

### ISSUE THREAD

**Issue by splittedvik** [mayankk2308/set-egpu#3]
Hey, I get a zoomed in Video in Intro Screen when activating the Script for Premiere Pro on a 2017 MacBook Pro with the internal display.

I can see in the activity monitor that it uses the eGPU but the video playback is zoomed in a laggy.

![bildschirmfoto 2018-07-29 um 19 51 11](https://user-images.githubusercontent.com/41874616/43369149-18737f9a-9369-11e8-8b94-16d1876f605e.jpg)

**Comment by mayankk2308** [comment]
This is not an issue with the script itself, but with the app + macOS eGPU preference settings. The script only helps in setting that preference, nothing more. Consider checking egpu.io forums for users facing a similar issue and if they managed to resolve it. Apologies for not being able to help - I don’t use Premiere so I can’t test myself..
