### ISSUE TITLE
[Question] How to uninstall the script?

### ISSUE THREAD

**Issue by rickycc** [mayankk2308/set-egpu#4]
How do I uninstall if something has gone wrong?

**Comment by mayankk2308** [comment]
https://egpu.io/forums/mac-setup/potentially-accelerate-all-applications-on-egpu-macos-10-13-4/paged/3/#post-41809

Should be sufficient.

**Comment by rickycc** [comment]
@mayankk2308 Appreciates your swift reply. The script works flawlessly!

**Comment by mayankk2308** [comment]
✌️Closed.

**Comment by mayankk2308** [comment]
**V1.2.0+** of the script includes the option to uninstall all components of the script and any changes made completely.
