### ISSUE TITLE
Could Not set eGPU for any app 

### ISSUE THREAD

**Issue by Zer0xPoint** [mayankk2308/set-egpu#5]
2016 13 touch bar
gaming box 1060 3g
mojave

**Comment by mayankk2308** [comment]
Mojave has this built-in, and the script needs an update for post-beta 5.

Please provide more specific information and test results.

**Comment by mayankk2308** [comment]
It would seem that newer Mojave betas do not respect application-provided eGPU preferences for some reason. Issue under investigation. I have successfully created an alternative, but not optimal solution using user interface manipulation to prefer eGPU using the *Mojave* way.

**Comment by Zer0xPoint** [comment]
10.14 Beta (18A377a)
gigabyte gaming box tb3
I use refind to solve code 12 in bootcamp,egpu works fine.
Boot direct from 10.14, The system did not find any egpu after run set-egpu script.
Then I try to install nvidia driver from Benjamin-Dobell's script and patch driver with purge-wrangler.sh, Still nothing happend.
Am I did something wrong?

**Comment by Zer0xPoint** [comment]
appreciate if u can provide an alternative way.

**Comment by mayankk2308** [comment]
NVIDIA eGPUs do not work in Mojave (unless you are using **GTX 780** or older) until NVIDIA releases web drivers for it.

Closing this issue. Mojave has built-in capability to set eGPU - an alternative will be implemented in the script if necessary.
