### ISSUE TITLE
Application with multiple bundle IDs

### ISSUE THREAD

**Issue by Smirow** [mayankk2308/set-egpu#9]
Hi,

Many apps have different sub bundle IDs (Chrome with Chrome Helper, Games Launcher/Client...) and setting `GPUSelectionPolicy` to the main one isn't enough. 
We have to set `GPUSelectionPolicy` for each bundle id to make it work.

I can't find of an easy way to script it (maybe going through all `Info.plist` in the app directory and finding the `CFBundleIdentifier` for each one).

**Comment by mayankk2308** [comment]
Thank you for bringing this up. In the case of game launcher/client, setting the preference for the game itself is typically sufficient. Unfortunately, the number of variables of what works and what doesn't is really high and one may not be able to script in all the possibilities. Factor in the fact that this method does not work in Mojave, there is little motivation to develop this further. I shall keep an eye out for this. I really need a nice full free day to work on set-eGPU.
